[git_status]
conflicted = 'ğŸ³'
ahead = 'ğŸğŸ’¨'
behind = 'ğŸ˜°'
diverged = 'ğŸ˜µ'
untracked = 'ğŸ¤·â€'
stashed = 'ğŸ“¦'
modified = 'ğŸ“'
renamed = 'ğŸ‘…'
deleted = 'ğŸ—‘'

[git_status.staged]
value = '++'
style = 'green'

[git_status.staged_count]
enabled = true
style = 'green'

[git_branch]
symbol = 'ğŸŒ± '

[time]
disabled = false
format = 'ğŸ•™[ %T ]'
